# this rest api for making data content

###
GET http://localhost:3010/api/homepages

###
GET http://localhost:3010/api/display/types
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0
###
POST http://localhost:3010/api/display/types
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "title": "rectangle",
    "status": 1
}

###
POST http://localhost:3010/api/display/types/1
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "title": "rectangles",
    "status": 1
}

### Get Display Types with Pagination and Filtering ###
GET http://localhost:3010/api/display/types?page=1&limit=10&status=1
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0


###
POST http://localhost:3010/api/contents
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "title": "pestapora 1",
    "status": 1,
    "display_types_id": 1
}

###
POST http://localhost:3010/api/contents/1
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMTA1OTA1MSwiZXhwIjoxNzMxNjYzODUxfQ.Ekph_z5fi-CbZqFhHqPdGT1Vnfur3st9ALE6GqSY-PE

{
    "title": "pestapora 2",
    "status": 1,
    "display_types_id": 1
}

### Get Display Types with Pagination and Filtering ###
# GET http://localhost:3010/api/contents?page=1&limit=10&status=1&title=pestapora
GET http://localhost:3010/api/contents?page=1&limit=10&status=1
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

###
POST http://localhost:3010/api/event/organizers
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "name": "P didy Corporate",
    "detail": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris turpis sem, posuere gravida nibh a, vestibulum finibus neque. Phasellus pulvinar metus erat, nec bibendum eros ultrices sed. Sed sagittis turpis id nisl auctor aliquam ac sed nisl. Mauris vitae nisl et tortor fermentum volutpat. Aenean et ultrices erat. Aliquam erat volutpat. Vivamus tempor ultrices diam, rutrum egestas mi euismod non. Cras elementum nisl quis ullamcorper aliquam. Vivamus maximus ante urna, nec sagittis dolor dignissim quis."
}

###
GET http://localhost:3010/api/event/organizers?name=p
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

###
POST http://localhost:3010/api/type/content/detail
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "name": "Festival"
}

###
GET http://localhost:3010/api/type/content/detail?name=festival
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

###
POST http://localhost:3010/api/tags
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "title": "Festival"
}

###
GET http://localhost:3010/api/tags?title=festival
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0


###
POST http://localhost:3010/api/actress
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "name": "Soraya",
    "gender": 1,
    "image": "https://linebank.co.id/blog/wp-content/uploads/2024/09/pestapora-2024-LB-Blog-jpg.webp"
}

###
GET http://localhost:3010/api/actress
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0


###
POST http://localhost:3010/api/content/details
Content-Type: application/json
x-api-key: ku4jaK6v%$gd364GAga5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2QiOjAsInVpcCI6IjEyNy4wLjAuMSIsInVhZyI6InZzY29kZS1yZXN0Y2xpZW50IiwidG9rZW4iOiJleUowYjJRaU9qQXNJblZwY0NJNklqRXlOeTR3TGpBdU1TSXNJblZoWnlJNkluWnpZMjlrWlMxeVpYTjBZMnhwWlc1MEluMWhabk5oT1NSQ1JrVTRORE15WW10cVpqTW9LaWg1TWlrcCIsImlhdCI6MTczMDk0NzEwNywiZXhwIjoxNzMxNTUxOTA3fQ.6Ex2saYkRLdbpHMrt87lRY9hgvOXsNDClk8njhsM4O0

{
    "title": "Pestapora 2024 & menjadi yang terbaik loh 100%",
    "schedule_start": "2024-11-06T12:00:00Z",
    "schedule_end": "2024-11-07T12:00:00Z",
    "date_start": "2024-11-07T12:00:00Z",
    "date_end": "2024-11-07T12:00:00Z",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris turpis sem, posuere gravida nibh a, vestibulum finibus neque. Phasellus pulvinar metus erat, nec bibendum eros ultrices sed. Sed sagittis turpis id nisl auctor aliquam ac sed nisl. Mauris vitae nisl et tortor fermentum volutpat. Aenean et ultrices erat. Aliquam erat volutpat. Vivamus tempor ultrices diam, rutrum egestas mi euismod non. Cras elementum nisl quis ullamcorper aliquam. Vivamus maximus ante urna, nec sagittis dolor dignissim quis.",
    "image": "https://linebank.co.id/blog/wp-content/uploads/2024/09/pestapora-2024-LB-Blog-jpg.webp",
    "vanues_id": 1,
    "contents_id": 2,
    "event_organizers_id": 1,
    "is_trending": 0,
    "status": 2,
    "type_content_details_id": 1,
    "actress": [
        {
            "id": "1"
        },
        {
            "id": "1"
        }
    ],
    "tags": [
        {
            "id": "1"
        }
    ]
}

